name: Auto Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check modified files
        id: check_files
        uses: dorny/paths-filter@v2
        with:
          filters: |
            only_allowed:
              - '2025webi.md'
            other_files:
              - '!2025webi.md'
              - '**/*'

      - name: Validate content format
        id: validate_content
        if: ${{ steps.check_files.outputs.only_allowed == 'true' && steps.check_files.outputs.other_files == 'false' }}
        run: |
          git diff origin/${{ github.base_ref }} ${{ github.event.pull_request.head.sha }} -- 2025webi.md > diff.txt
          
          # Check if the diff contains added lines with the correct format
          ADDED_LINES=$(grep -E '^\+' diff.txt | grep -v '^\+\+\+' || echo "")
          
          # Regular expression to match the format: - [Nome](https://github.com/username)
          FORMAT_REGEX='^\+- \[[A-Za-z ]+\]\(https:\/\/github\.com\/[A-Za-z0-9_-]+\)
          
          # Check if any added line matches the required format
          if echo "$ADDED_LINES" | grep -E "$FORMAT_REGEX" > /dev/null; then
            echo "Valid format found in added content"
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "No valid format found in added content"
            echo "valid=false" >> $GITHUB_OUTPUT
          fi

      - name: Auto approve and merge if valid content
        if: ${{ steps.check_files.outputs.only_allowed == 'true' && steps.check_files.outputs.other_files == 'false' && steps.validate_content.outputs.valid == 'true' }}
        run: |
          echo "Only 2025webi.md was modified with correct format, proceeding with auto-approval and merge"
          gh pr review ${{ github.event.pull_request.number }} --approve
          gh pr merge ${{ github.event.pull_request.number }} --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment if format is invalid
        if: ${{ steps.check_files.outputs.only_allowed == 'true' && steps.check_files.outputs.other_files == 'false' && steps.validate_content.outputs.valid != 'true' }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "O formato da entrada adicionada não segue o padrão requerido. Por favor, siga o formato: '- [Nome da Pessoa](https://github.com/username)'"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment if other files are modified
        if: ${{ steps.check_files.outputs.other_files == 'true' }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Este PR modificou outros arquivos além do 2025webi.md. O auto-merge só é permitido quando apenas o arquivo 2025webi.md é modificado."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}