name: Auto Merge PR for 2025webi.md

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main # Substitua por 'master' se o branch principal for diferente

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código do PR
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Verificar se apenas o arquivo 2025webi.md foi modificado
      - name: Check changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} HEAD)
          echo "Changed files: $CHANGED_FILES"
          if [[ "$CHANGED_FILES" != "2025webi.md" ]]; then
            echo "PR modifies files other than 2025webi.md"
            exit 1
          fi

      # Verificar se a modificação é uma única linha no formato correto
      - name: Check line format
        run: |
          DIFF=$(git diff origin/${{ github.base_ref }} HEAD -- 2025webi.md)
          ADDED_LINES=$(echo "$DIFF" | grep -E '^\+' | grep -v '^\+\+\+' | wc -l)
          VALID_LINE=$(echo "$DIFF" | grep -E '^\+ *- *\[.*\][](https://github\.com/.*\)')
          if [[ $ADDED_LINES -ne 1 || -z "$VALID_LINE" ]]; then
            echo "PR does not add exactly one line in the format: - [Name](https://github.com/username)"
            exit 1
          fi

      # Configurar o GitHub CLI
      - name: Setup GitHub CLI
        uses: actions4gh/setup-gh@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Habilitar auto-merge no PR
      - name: Enable auto-merge
        run: |
          gh pr merge --auto --merge ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}