name: AutoAceitar PRs Simples

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validar-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verifica mudanças
        id: diff
        run: |
          FILES=$(git diff --name-only origin/main)
          echo "FILES=$FILES" >> $GITHUB_ENV
          echo "::set-output name=files::$FILES"

      - name: Validar regras da PR
        run: |
          if [[ "$FILES" != "2025webi.md" ]]; then
            echo "Erro: Apenas o arquivo 2025webi.md pode ser alterado"
            exit 1
          fi

          ADDED_LINES=$(git diff origin/main -- 2025webi.md | grep "^+" | grep -v "^+++" || true)

          if [[ -z "$ADDED_LINES" ]]; then
            echo "Erro: Nenhuma linha foi adicionada ao arquivo 2025webi.md"
            exit 1
          fi

          VALID=0
          while read -r LINE; do
            if [[ "$LINE" =~ ^\+\- \[[^]]+\]\(https://github\.com/[^)]+\)$ ]]; then
              VALID=$((VALID+1))
            fi
          done <<< "$ADDED_LINES"

          if [[ "$VALID" -lt 1 ]]; then
            echo "Erro: Nenhuma linha adicionada está no formato correto."
            exit 1
          fi

      - name: Ativar auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
