name: AutoAceitar PRs Simples

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validar-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validar regras da PR
        shell: bash
        run: |
          # Verifica se apenas 2025webi.md foi alterado
          MODIFIED=$(git diff --name-only origin/main | xargs || true)

          # Debugging output
          echo "Arquivos modificados: $MODIFIED"

          if [[ "$MODIFIED" != "2025webi.md" ]]; then
            echo "Erro: Apenas o arquivo 2025webi.md pode ser alterado"
            exit 1
          fi

          # Coleta linhas adicionadas
          ADDED_LINES=$(git diff origin/main -- 2025webi.md | grep "^+" | grep -v "^+++" || true)

          if [[ -z "$ADDED_LINES" ]]; then
            echo "Erro: Nenhuma linha foi adicionada ao arquivo 2025webi.md"
            exit 1
          fi

          # Verifica se pelo menos uma linha está no formato correto
          VALID=0
          while read -r LINE