name: Valida Pull Request

on:
  pull_request:
    paths:
      - '2025webi.md'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Pega o histórico do commit anterior

      - name: Verifica se apenas o arquivo 2025webi.md foi alterado
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
          if [ "$CHANGED_FILES" != "2025webi.md" ]; then
            echo "Erro: Apenas o arquivo 2025webi.md pode ser modificado."
            echo "Arquivos alterados: $CHANGED_FILES"
            exit 1
          fi

      - name: Verifica se o formato da linha adicionada está correto
        run: |
          ADDED_LINES=$(git diff origin/main...HEAD -- 2025webi.md | grep '^+[^+]' || true)
          echo "$ADDED_LINES" > added.txt
          
          MATCHES=$(grep -E '^\+ - \[.+\]\(https://github\.com/.+\)' added.txt | wc -l)
          
          if [ "$MATCHES" -lt 1 ]; then
            echo "Erro: Deve ser adicionada ao menos uma linha no formato:"
            echo "- [Seu Nome](https://github.com/seuusuario)"
            exit 1
          fi
